apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail.yaml: |
    server:
      http_listen_port: 3101
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://10.148.15.213:3100/loki/api/v1/push

    scrape_configs:
      - job_name: container-logs
        static_configs:
          - targets: [localhost]
            labels:
              job: container-logs
              __path__: /var/log/containers/*.log

        pipeline_stages:
          - regex:
              source: filename
              expression: '^(?P<pod>.+)_(?P<namespace>.+)_(?P<container>.+)-(?P<container_id>.+)\.log$'

          - labels:
              pod:
              namespace:
              container:
              container_id:

          - json:
              expressions:
                level: level
                trace_id: trace_id

          - labels:
              level:
              trace_id:
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      containers:
        - name: promtail
          image: grafana/promtail:2.9.1
          args:
            - -config.file=/etc/promtail/promtail.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: pods
              mountPath: /var/log/pods
              readOnly: true
            - name: containers
              mountPath: /var/lib/containers
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: pods
          hostPath:
            path: /var/log/pods
        - name: containers
          hostPath:
            path: /var/lib/containers

---
# Ingress yang benar untuk mengarah ke LOKI DI VM LUAR
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-external
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: loki.wandoor.local
      http:
        paths:
          - path: /loki
            pathType: Prefix
            backend:
              service:
                name: loki-proxy
                port:
                  number: 80

---
# Service proxy untuk meneruskan request dari ingress ke Loki external VM
apiVersion: v1
kind: Service
metadata:
  name: loki-proxy
  namespace: monitoring
spec:
  type: ExternalName
  externalName: 10.148.15.213  # <- Ganti dengan IP Loki VM kamu
  ports:
    - port: 80
      targetPort: 3100